"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path

from . import production_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = production_settings.SECRET_KEY


DEBUG = production_settings.DEBUG


ALLOWED_HOSTS = production_settings.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = production_settings.INSTALLED_APPS

MIDDLEWARE = production_settings.MIDDLEWARE

ROOT_URLCONF = production_settings.ROOT_URLCONF

TEMPLATES = production_settings.TEMPLATES

WSGI_APPLICATION = production_settings.WSGI_APPLICATION


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = production_settings.DATABASES


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = production_settings.AUTH_PASSWORD_VALIDATORS


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = production_settings.LANGUAGE_CODE

TIME_ZONE = production_settings.TIME_ZONE

USE_I18N = production_settings.USE_I18N

USE_TZ = production_settings.USE_TZ


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = production_settings.STATIC_URL
MEDIA_URL = production_settings.MEDIA_URL

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = production_settings.DEFAULT_AUTO_FIELD

# Authentication

AUTH_USER_MODEL = production_settings.AUTH_USER_MODEL

# Caching

CACHES = production_settings.CACHES

# Django REST Framework

REST_FRAMEWORK = production_settings.REST_FRAMEWORK
SPECTACULAR_SETTINGS = production_settings.SPECTACULAR_SETTINGS

# Security

SECURE_HSTS_SECONDS = 259200
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
