# Generated by Django 4.1.1 on 2022-09-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_teacherclassroom_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentclassroom",
            name="student",
        ),
        migrations.AddField(
            model_name="studentclassroom",
            name="classroom",
            field=models.CharField(
                default="", max_length=255, verbose_name="classroom"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="subject"),
        ),
        migrations.AlterField(
            model_name="classroomgrade",
            name="average",
            field=models.FloatField(
                default=0.0, max_length=255, verbose_name="average"
            ),
        ),
        migrations.AlterField(
            model_name="classroomstudent",
            name="student",
            field=models.CharField(max_length=255, verbose_name="student"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gradedetail",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="teacherclassroom",
            name="classroom",
            field=models.CharField(max_length=255, verbose_name="class room"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="register",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="registration number"
            ),
        ),
    ]
