# Generated by Django 4.1.1 on 2022-09-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_studentclassroom_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentclassroom",
            name="classroom",
            field=models.CharField(max_length=255, verbose_name="classroom"),
        ),
    ]
